<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Jeremy Lowe" />


<title>Harris Lab R Training Module</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/table1-1.0/table1_defaults.css" rel="stylesheet" />
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Harris Lab R Training Module</h1>
<h4 class="author">Jeremy Lowe</h4>
<h4 class="date">6/7/2021</h4>

</div>


<style type="text/css">
.code-style {
  background-color: snow;
  border: 1px solid black;
  font-weight: bold
}
</style>
<center>
<img src="files/horst_rstudio_air.png" alt="Image credit: Allison Horst" /> Image Credit: Allison Horst
</center>
<hr />
<div id="introduction" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>This training module was created for the Harris Lab to aid in developing publication-ready figures, tables, and more. It assumes you have a basic knowledge of R including importing data, ‘tidying’ it, and basic analyses. It is by no means meant to reinvent the wheel when it comes to more detailed trainings (like the ones found in <a href="https://r4ds.had.co.nz/index.html">the R for Data Science textbook</a>.) More general resources for the lab can also be found in the <a href="https://docs.google.com/document/d/1F6vYfGr8zeFSx2Wo0bD8fEipSpl7VPpqFNFkbbOOw6I/edit#heading=h.ft1w0w4x8r7h">Harris Lab R Resources document</a>.</p>
<p>For this small module, we will be using data from the <em>Iris</em> dataset, which is included in the Tidyverse package. The dataset actually contains data from a study conducted in 1936 by Ronald Fisher, so if you are interested in learning more, you can view it <a href="https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1469-1809.1936.tb02137.x">here</a>. It contains measurements from three different irises that characterizes different dimensions for each. The image below gives you an idea of the data we’re looking at:</p>
<p> </p>
<center>
<p><img src="files/iris_sepal_petal.png" /></p>
</center>
<p> </p>
<p>For later analyses in this tutorial, we will switch to using a practice dataset focused on respiratory health provided by <a href="https://statslectures.com/r-scripts-datasets">Mike Marin of the University of British Columbia</a>. This dataset presents information regarding lung capacity, age, smoker status, gender, and more. It is a wonderful dataset to apply some ideas health analyses to!</p>
<p> </p>
<p>The code chunk below demonstrates how to load the data and other relevant packages into the environment:</p>
<pre class="r code-style"><code># Loading in relevant packages, some of these will be used later
library(tidyverse)
library(table1)
library(kableExtra)
library(patchwork)


# Loading data into the environment
# You will likely use the read_csv() function in Tidyverse to load other datasets.
data(iris)

#Dataset provided by Mike Marin of University of British Columbia 
lung_cap &lt;- readr::read_csv(&#39;https://raw.githubusercontent.com/jlowe-git/Harris_Lab_R_Resources/main/LungCapData.csv&#39;)

# Take a peek at the data to see what we&#39;re working with!
head(iris)</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<pre class="r code-style"><code>head(lung_cap)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   LungCap   Age Height Smoke Gender Caesarean
##     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    
## 1    6.48     6   62.1 no    male   no       
## 2   10.1     18   74.7 yes   female no       
## 3    9.55    16   69.7 no    female yes      
## 4   11.1     14   71   no    male   no       
## 5    4.8      5   56.9 no    male   no       
## 6    6.22    11   58.7 no    female no</code></pre>
<p> </p>
<hr />
<p> </p>
</div>
<div id="r-markdown" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> R Markdown</h1>
<p>R Markdown is a literate programming file within RStudio that can take advantage of html formatting and more to produce amazing tables, visualizations, dashboards, reports, and more. It was used to create the document you are viewing right now as well! This tutorial relies on packages that make use of the html formatting in R Markdown, so it is recommended you use an R Markdown file when following along. A helpful tutorial on R Markdown can be found within <a href="https://r4ds.had.co.nz/r-markdown.html">Chapter 27</a> of the R for Data Science textbook linked in the previous section, but I will also walk through the basics in this section.</p>
<p>First, you will open an R Markdown file in the same manner you would a typical R source file in R Studio; simply go to File -&gt; New File -&gt; R Markdown. You will see the following prompt open:</p>
<center>
<div class="figure">
<img src="files/rmarkdown1.PNG" alt="" />
<p class="caption">R Markdown New File Prompt</p>
</div>
</center>
<p> </p>
<p>On this page, you will see that you have the option to create an output in either html, pdf, or doc files types. For our purposes, we will be using the html output. If you have a need for another output version, there are helpful resources in <a href="https://r4ds.had.co.nz/r-markdown.html">Chapter 27</a> of the R for Data Science textbook!</p>
<p>After opening the new R Markdown file, you will notice the file is already populated with some code and text. This is the standard R Markdown template. You can delete everything I have highlighted below so your file looks relatively bare except for the header and chunk settings.</p>
<p> </p>
<center>
<p><img src="files/rmarkdown2.PNG" /></p>
<p>  You can delete the highlighted portion to be left with:  </p>
<p><img src="files/rmarkdown3.PNG" /></p>
</center>
<p> </p>
<p>Perfect! Now let’s walk through the structure of an R Markdown file…</p>
 
<center>
<img src="files/rmarkdown5.png" />
</center>
<p> </p>
<p>First, the YAML (Yes Another Markdown Language) Header stores pertinent information regarding the file like author and title, as well as various options for how to generate the output. The output options can become much more complex and involve table of contents, CSS styling, and more. The sky is the limit for the number of options you can include in this header.</p>
<p>Next, you have the ability to change options for all of the code chunks. The ‘echo’ option allows you to either hide or display code chunks in your report output. Again, countless other options exist and can be explored in <a href="https://r4ds.had.co.nz/r-markdown.html">Chapter 27</a> of the R for Data Science textbook.</p>
<p>After the code chunk settings, I’ve written some general text. This text is just simple text, no code included. It can be used to organize ideas for yourself or your audience!</p>
<p>Next, the most important part. I’ve shown how to include a code chunk. The easiest way is to use the hotkey (CTRL + Alt + I) to ‘Insert’ the chunk. Code chunks are where you can include all of your code, and each chunk is compartmentalized. Each chunk has a title and settings included within the { } brackets.</p>
<p>Lastly, to generate the report, you want to ‘knit’ the R Markdown file. Knitting everything converts your R Markdown document into a neatly formatted html report! You’ll want to make sure you have the knitr package downloaded prior to attempting to knit your document. To knit, simply click the small ‘knit’ button located at the top of the file. If everything is right, it should generate an html file in the same file storage as your R Markdown document and open the html file automatically. Let’s take a look at the example shown!</p>
 
<center>
<img src="files/rmarkdown6.PNG" />
</center>
<p> </p>
<p>And that’s the quick crash course on R Markdown. Once you become handy with R Markdown, you’ll realize how many doors it opens to seamlessly generate code and formatted figures, tables, and more.</p>
<p> </p>
<hr />
<p> </p>
</div>
<div id="tables" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> Tables</h1>
<p>For any data analysis, being able to calculate descriptive statistics and represent them in a table is a must. This section will walk you through the <a href="https://benjaminrich.github.io/table1/vignettes/table1-examples.html">Table1</a> package, a useful tool in representing descriptive statistics across several variables, as well as <a href="https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Installation">Kable</a>, included in the <a href="https://yihui.org/knitr/">Knitr</a> package, which offers abilities to transform dataframes/tibbles into well-formatted and meaningful tables. Just to reiterate, you should be working within an R Markdown file to create an html output; regular R source files will not do the trick.</p>
<p>First, with our <em>Iris</em> dataset, we’re interested to learn about some of the measures of central tendency (mean, median, standard deviation, etc.) of the provided data. We have variables representing the sepal length and width, petal length and width, and the species of Iris.</p>
<p> </p>
<div id="table1" class="section level2" number="3.1">
<h2 number="3.1"><span class="header-section-number">3.1</span> Table1</h2>
<p>To get a quick view at descriptive statistics, we’ll use the following code and the Table1 package.</p>
<pre class="r code-style"><code># First, I need to ensure my variables are the right data type.
str(iris)</code></pre>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<pre class="r code-style"><code># Based on the &#39;structure&#39; function above, I see I have 4 numeric variables and 1 factor variable, which is exactly what I need.

# Often, categorical data is represented as a character data type, but table1 prefers factor data types
# To change characters to factors, I could use the following code:
# iris$Species &lt;- factor(iris$Species)




# Creating basic table using table1 function
# Note: The variables I&#39;m interested in are included in a &#39;formula&#39; input:
# ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width
# All variables you want to calculate descriptive stats for are used in the table1() function this way
table1(~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width + Species, data = iris)</code></pre>
<div class="Rtable1"><table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(N=150)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'>Sepal.Length</td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>5.84 (0.828)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>5.80 [4.30, 7.90]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Sepal.Width</td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>3.06 (0.436)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>3.00 [2.00, 4.40]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Petal.Length</td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>3.76 (1.77)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>4.35 [1.00, 6.90]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Petal.Width</td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>1.20 (0.762)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>1.30 [0.100, 2.50]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Species</td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>setosa</td>
<td>50.0 (33.3%)</td>
</tr>
<tr>
<td class='rowlabel'>versicolor</td>
<td>50.0 (33.3%)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>virginica</td>
<td class='lastrow'>50.0 (33.3%)</td>
</tr>
</tbody>
</table>
</div>
<p> </p>
<p>Looks good! However, there are many more ways to customize the table1 output. For one, to gain some more meaningful insights, I could stratify my numerical data over the 3 species of Irises. Let’s say I am also interested in making this more publication ready, which means I need to change how my variable names appear in the table. Doing so would use the following code:</p>
<pre class="r code-style"><code># Adjusting the display of variable names
label(iris$Sepal.Length) &lt;- &quot;Sepal Length&quot;
label(iris$Sepal.Width) &lt;- &quot;Sepal Width&quot;
label(iris$Petal.Length) &lt;- &quot;Petal Length&quot;
label(iris$Petal.Width) &lt;- &quot;Petal Width&quot;

# Adjusting factor display names for each species
iris$Species &lt;- fct_recode(iris$Species,
  &quot;Setosa&quot; = &quot;setosa&quot;,
  &quot;Versicolor&quot; = &quot;versicolor&quot;,
  &quot;Virginica&quot; = &quot;virginica&quot;
)


# table1 output stratified by Iris species
table1(~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width | Species, data = iris)</code></pre>
<div class="Rtable1"><table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>Setosa<br><span class='stratn'>(N=50)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>Versicolor<br><span class='stratn'>(N=50)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>Virginica<br><span class='stratn'>(N=50)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(N=150)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'>Sepal Length</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>5.01 (0.352)</td>
<td>5.94 (0.516)</td>
<td>6.59 (0.636)</td>
<td>5.84 (0.828)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>5.00 [4.30, 5.80]</td>
<td class='lastrow'>5.90 [4.90, 7.00]</td>
<td class='lastrow'>6.50 [4.90, 7.90]</td>
<td class='lastrow'>5.80 [4.30, 7.90]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Sepal Width</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>3.43 (0.379)</td>
<td>2.77 (0.314)</td>
<td>2.97 (0.322)</td>
<td>3.06 (0.436)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>3.40 [2.30, 4.40]</td>
<td class='lastrow'>2.80 [2.00, 3.40]</td>
<td class='lastrow'>3.00 [2.20, 3.80]</td>
<td class='lastrow'>3.00 [2.00, 4.40]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Petal Length</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>1.46 (0.174)</td>
<td>4.26 (0.470)</td>
<td>5.55 (0.552)</td>
<td>3.76 (1.77)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>1.50 [1.00, 1.90]</td>
<td class='lastrow'>4.35 [3.00, 5.10]</td>
<td class='lastrow'>5.55 [4.50, 6.90]</td>
<td class='lastrow'>4.35 [1.00, 6.90]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Petal Width</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>0.246 (0.105)</td>
<td>1.33 (0.198)</td>
<td>2.03 (0.275)</td>
<td>1.20 (0.762)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>0.200 [0.100, 0.600]</td>
<td class='lastrow'>1.30 [1.00, 1.80]</td>
<td class='lastrow'>2.00 [1.40, 2.50]</td>
<td class='lastrow'>1.30 [0.100, 2.50]</td>
</tr>
</tbody>
</table>
</div>
<p> </p>
<p>Nice! We can begin to see some of the differences across the different types of species and the table looks great.</p>
<p> </p>
<p>Next, let’s take a look at the descriptive statistics of our respiratory health dataset. To do so, we will be using Table1 again.</p>
<pre class="r code-style"><code># Adjusting the name of one variable
label(lung_cap$LungCap) &lt;- &quot;Lung Capacity&quot;

# We need to turn some variables from character data types into factor data types
lung_cap$Smoke &lt;- factor(lung_cap$Smoke)
lung_cap$Gender &lt;- factor(lung_cap$Gender)
lung_cap$Caesarean &lt;- factor(lung_cap$Caesarean)


# Next, we will represent it in Table1 and stratify by gender
table1(~ LungCap + Age + Height + Smoke + Caesarean | Gender, data = lung_cap)</code></pre>
<div class="Rtable1"><table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>female<br><span class='stratn'>(N=358)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>male<br><span class='stratn'>(N=367)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(N=725)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'>Lung Capacity</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>7.41 (2.56)</td>
<td>8.31 (2.68)</td>
<td>7.86 (2.66)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>7.75 [0.507, 13.1]</td>
<td class='lastrow'>8.35 [1.18, 14.7]</td>
<td class='lastrow'>8.00 [0.507, 14.7]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Age</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>12.4 (3.96)</td>
<td>12.2 (4.05)</td>
<td>12.3 (4.00)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>13.0 [3.00, 19.0]</td>
<td class='lastrow'>12.0 [3.00, 19.0]</td>
<td class='lastrow'>13.0 [3.00, 19.0]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Height</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>63.8 (7.03)</td>
<td>65.8 (7.24)</td>
<td>64.8 (7.20)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>64.4 [45.3, 79.8]</td>
<td class='lastrow'>66.1 [47.8, 81.8]</td>
<td class='lastrow'>65.4 [45.3, 81.8]</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Smoke</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>no</td>
<td>314 (87.7%)</td>
<td>334 (91.0%)</td>
<td>648 (89.4%)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>yes</td>
<td class='lastrow'>44.0 (12.3%)</td>
<td class='lastrow'>33.0 (9.0%)</td>
<td class='lastrow'>77.0 (10.6%)</td>
</tr>
<tr>
<td class='rowlabel firstrow'>Caesarean</td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>no</td>
<td>279 (77.9%)</td>
<td>282 (76.8%)</td>
<td>561 (77.4%)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>yes</td>
<td class='lastrow'>79.0 (22.1%)</td>
<td class='lastrow'>85.0 (23.2%)</td>
<td class='lastrow'>164 (22.6%)</td>
</tr>
</tbody>
</table>
</div>
<p>What I’ve shown here just scratches the surface of <a href="https://benjaminrich.github.io/table1/vignettes/table1-examples.html">Table1</a>, and I recommend checking out the documentation to see more of what it is capable of.</p>
<p> </p>
</div>
<div id="kable" class="section level2" number="3.2">
<h2 number="3.2"><span class="header-section-number">3.2</span> Kable</h2>
<p>The kbl() function is included in the knitr package and provides the ability to transform dataframes/tibbles into html formatted tables. It is perfect for developing tables that are easily readable for publications, presentations, reports, etc.</p>
<p>Say we want to represent the descriptive statistics again, but this time using kbl(). To do so, we could use the following code:</p>
<pre class="r code-style"><code># Creating descriptive statistics
iris_kable &lt;- group_by(iris, Species) %&gt;%
  summarise(
    Count = n(),
    &quot;Sepal Width Mean&quot; = mean(Sepal.Width, na.rm = TRUE),
    &quot;Sepal Width SD&quot; = sd(Sepal.Width, na.rm = TRUE),
    &quot;Petal Width Mean&quot; = mean(Petal.Width, na.rm = TRUE),
    &quot;Petal Width SD&quot; = sd(Petal.Width, na.rm = TRUE),
    &quot;Sepal Length Mean&quot; = mean(Sepal.Length, na.rm = TRUE),
    &quot;Sepal Length SD&quot; = sd(Sepal.Length, na.rm = TRUE),
    &quot;Petal Length Mean&quot; = mean(Petal.Length, na.rm = TRUE),
    &quot;Petal Length SD&quot; = sd(Petal.Length, na.rm = TRUE),
  )

# Representing in a Kable
iris_kable %&gt;%
  kbl() %&gt;%
  add_header_above(c(&quot;Descriptive Statistics of Iris Species (N = 150)&quot; = 10)) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;), full_width = F, font_size = 12)</code></pre>
<table class="table table-striped table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="10">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Descriptive Statistics of Iris Species (N = 150)
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Species
</th>
<th style="text-align:right;">
Count
</th>
<th style="text-align:right;">
Sepal Width Mean
</th>
<th style="text-align:right;">
Sepal Width SD
</th>
<th style="text-align:right;">
Petal Width Mean
</th>
<th style="text-align:right;">
Petal Width SD
</th>
<th style="text-align:right;">
Sepal Length Mean
</th>
<th style="text-align:right;">
Sepal Length SD
</th>
<th style="text-align:right;">
Petal Length Mean
</th>
<th style="text-align:right;">
Petal Length SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Setosa
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
3.428
</td>
<td style="text-align:right;">
0.3790644
</td>
<td style="text-align:right;">
0.246
</td>
<td style="text-align:right;">
0.1053856
</td>
<td style="text-align:right;">
5.006
</td>
<td style="text-align:right;">
0.3524897
</td>
<td style="text-align:right;">
1.462
</td>
<td style="text-align:right;">
0.1736640
</td>
</tr>
<tr>
<td style="text-align:left;">
Versicolor
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
2.770
</td>
<td style="text-align:right;">
0.3137983
</td>
<td style="text-align:right;">
1.326
</td>
<td style="text-align:right;">
0.1977527
</td>
<td style="text-align:right;">
5.936
</td>
<td style="text-align:right;">
0.5161711
</td>
<td style="text-align:right;">
4.260
</td>
<td style="text-align:right;">
0.4699110
</td>
</tr>
<tr>
<td style="text-align:left;">
Virginica
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
2.974
</td>
<td style="text-align:right;">
0.3224966
</td>
<td style="text-align:right;">
2.026
</td>
<td style="text-align:right;">
0.2746501
</td>
<td style="text-align:right;">
6.588
</td>
<td style="text-align:right;">
0.6358796
</td>
<td style="text-align:right;">
5.552
</td>
<td style="text-align:right;">
0.5518947
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>As you can see, we are able to represent the descriptive statistics in a well-formatted table. Table1 still might be the better package for descrptive statistics in this case, but this serves as a good example of what Kable is capable of!</p>
<p>Another table you will likely find yourself needing to create are contingency tables (also known as cross-tabulations). In environmental health research, we are often wanting to compare different groups of participants based on outcomes or characteristics. Kable offers a quick way to create cross-tabulations across several variables!</p>
<p>For our example, we will create a new binary variable to represent if the iris has a sepal width that is below (coded as 0) or above (coded as 1) the median value overall across the 150 samples. After this new variable is created, we will create a cross-tabulation to gain understanding into which species has the greatest number with an above-median sepal width. This could be a quick way to infer how species correlates to sepal width.</p>
<pre class="r code-style"><code># Creating new binary variable to represent if an iris has an above/below median sepal width
sepal_width_median &lt;- median(iris$Sepal.Width)
iris &lt;- mutate(iris, Sepal.Width.Median = if_else(iris$Sepal.Width &lt; sepal_width_median, &quot;Below Median&quot;, &quot;Above Median&quot;))

# Creating a cross-tab representation of the species of irises and if they have an above or below median sepal width
#First, creating a small dataframe with the variables of interest
iris_kable &lt;- iris%&gt;%
  select(Species, Sepal.Width.Median)
#Changing the variable names to be more meaningful
names(iris_kable) &lt;- c(&quot;Species&quot;, &quot;Above/Below Median Sepal Width&quot;)
#Next, creating the cross-tab using kable
iris_kable%&gt;%
  group_by(Species, `Above/Below Median Sepal Width`)%&gt;%
  summarize(n=n())%&gt;%
  spread(Species, n)%&gt;%
  kable()%&gt;%
  add_header_above(c(&quot; &quot; = 1, &quot;Species&quot; = 3))%&gt;%
  add_header_above(c(&quot;Cross-tabulation of Iris Species and sepal Width (N = 150)&quot; = 4))%&gt;%
  kable_styling(bootstrap_options = c(&quot;condensed&quot;), full_width = F, font_size = 12)</code></pre>
<table class="table table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Cross-tabulation of Iris Species and sepal Width (N = 150)
</div>
</th>
</tr>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Species
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Above/Below Median Sepal Width
</th>
<th style="text-align:right;">
Setosa
</th>
<th style="text-align:right;">
Versicolor
</th>
<th style="text-align:right;">
Virginica
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Above Median
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
29
</td>
</tr>
<tr>
<td style="text-align:left;">
Below Median
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
21
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>From the cross-tabulation, we can see that the Setosa species has the greatest number of irises with a sepal width greater than the median. This cross-tabulation could help inform future statistical analyses to determine if there are any relationships between species and iris size.</p>
<p>Everything I have shown you thus far is a practical application of how to create tables in R Markdown. There is <em>much</em> more you can do than this and I encourage you to explore! Kable has many more opportunities to create custom tables through the <a href="https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Overview">KableExtra</a> package. Any time you have results from analyses (i.e. regression models, etc.), consider representing them in a Kable!</p>
<hr />
</div>
</div>
<div id="data-visualization-with-ggplot2" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Data Visualization with ggplot2</h1>
<p>R offers countless ways to create unique data visualizations. For our Iris dataset, it would be interesting to be able to expand upon our previous cross-tabulation to get a sense of how all of the dimensions of each species compares to one another. A straightforward way to do this would be to look at the distributions of dimensions for each species of Iris through box plots.</p>
<p>The following code makes use of the <a href="https://ggplot2-book.org/index.html">ggplot2</a> package that is included in the <em>Tidyverse</em>. The ggplot2 package offers incredibly useful tools to create data visualizations that go way beyond what basic R is capable of. An additional resource that contains more specific information on ggplot2 can be found <a href="https://r-graphics.org/">here</a>.</p>
<p>When working with ggplot2, you can imagine working with a recipe. Each ingredient, or layer, that you add to your plot will create something new until you have your final product. The code belows demonstrates a variety of ways to use these layers to create a beautiful final product!</p>
<pre class="r code-style"><code>#For this first step, we are simply sending our dataset to a ggplot2 object
plot_1 &lt;- iris%&gt;%
  ggplot() +
#Above, you will notice I used the + symbol. 
#The + symbol is how we add each layer to another!
#Now, we will create our boxplot layer
  geom_boxplot(aes(x = Species, y=Sepal.Width)) +
#Next, we will add labels to each axis
  labs(x = &quot;Species&quot;,
       y = &quot;Sepal Width (cm)&quot;) +
#Finally, we want to make it look pretty, so we&#39;ll add a theme
  theme_bw()



#We will now replicate the same plot for our other 3 measurements. 

plot_2 &lt;- iris%&gt;%
  ggplot() +
  geom_boxplot(aes(x = Species, y=Sepal.Length)) +
  labs(x = &quot;Species&quot;,
       y = &quot;Sepal Length (cm)&quot;) +
  theme_bw()


plot_3 &lt;- iris%&gt;%
  ggplot() +
  geom_boxplot(aes(x = Species, y=Petal.Width)) +
  labs(x = &quot;Species&quot;,
       y = &quot;Petal Width (cm)&quot;) +
  theme_bw()

plot_4 &lt;- iris%&gt;%
  ggplot() +
  geom_boxplot(aes(x = Species, y=Petal.Length)) +
  labs(x = &quot;Species&quot;,
       y = &quot;Petal Length (cm)&quot;) +
  theme_bw()


#Instead of having 4 individual figures, it&#39;d be more helpful to represent them in 1. 
#We will do so using the patchwork package. 
#The patchwork package is helpful for combining ggplot2 objects into 1!

library(patchwork)

#Patchwork can be expanded upon to create some really unique visualizations,
#so be sure to look more into it!


plot_1 + plot_2 + plot_3 + plot_4 + plot_annotation(title = &quot;Petal and Sepal Characteristics of Irises&quot;) </code></pre>
<p><img src="R_Training_Module_Harris_Lab_files/figure-html/Comparing%20distributions%20through%20a%20ggplot2%20visualization-1.png" style="display: block; margin: auto;" /></p>
<p> </p>
<p>Again, there are various geoms (or plot types) that can be used with ggplot2; it is all a matter of finding the right one to represent your data! This section of the tutorial was meant to give you an overview of ggplot, but we will continue to explore some of these other geoms alongside some of our analyses.</p>
<hr />
</div>
<div id="bivariate-data-analysis" class="section level1" number="5">
<h1 number="5"><span class="header-section-number">5</span> Bivariate Data Analysis</h1>
<p>With bivariate data analysis, we will be doing as the name says: analyzing the relationship between two variables. Below, I will present examples using ANOVA, Pearson’s Correlation, Pearson’s Chi-squared Test, McNemar Test, Student’s t Test, and Fisher’s Exact Test. The test you will use for your data depends on the type of data you have, and more information on how to choose the right statistical test can be found <a href="https://stats.idre.ucla.edu/other/mult-pkg/whatstat/">here</a>. Let’s try some examples.</p>
<p>   </p>
<div id="anova" class="section level2" number="5.1">
<h2 number="5.1"><span class="header-section-number">5.1</span> ANOVA</h2>
<p>Now say we are interested in determining if there is a difference in size of the sepal among different species. To do so, we will be using a one-way ANOVA. . The additional key assumptions for a one-way ANOVA are that the samples are independent of each other and randomly chosen, and that the dependent variable (in our case, sepal width or height) is normally distributed. At a basic level, a histogram can allow us to ‘eyeball’ it, but there are more rigorous statistical tests out there to determine normality. See the code below for how to create a basic histogram using the ggplot2 package:</p>
<pre class="r code-style"><code># Creating histogram of sepal width variable
plot_1 &lt;- iris %&gt;%
  ggplot() +
  geom_histogram(aes(y = Sepal.Width), binwidth = 0.1) +
  coord_flip() +
  labs(
    title = &quot;Sepal Width&quot;,
    y = &quot;Sepal Width (cm)&quot;,
    x = &quot;Frequency&quot;
  ) +
  theme_bw()

plot_1</code></pre>
<p><img src="R_Training_Module_Harris_Lab_files/figure-html/Checking%20for%20normality%20of%20iris%20data-1.png" style="display: block; margin: auto;" /></p>
<p> </p>
<p>As we can see, the data are fairly normally distributed, so we can feel more confident about using the one-way ANOVA to compare sepal width across species. Upon obtaining results though, we will want to represent them in a formatted table using the power of Kable so it can be shared to an audience. See the following code for how to do so:</p>
<pre class="r code-style"><code># Conducting one-way ANOVA and storing model for later formatting

anova_results &lt;- aov(data = iris, Sepal.Width ~ Species)

# The summary() function creates a crude output
summary(anova_results)</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  11.35   5.672   49.16 &lt;2e-16 ***
## Residuals   147  16.96   0.115                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As we can see from the ANOVA results, there is a statistically significant (P &lt; 0.05) relationship between Iris species and sepal width! Using tools from Kable or ggplot2, we can decide to represent these results further to better communicate this relationship and its magnitude of effect.</p>
<p>   </p>
</div>
<div id="pearsons-correlation-pearsons-r" class="section level2" number="5.2">
<h2 number="5.2"><span class="header-section-number">5.2</span> Pearson’s Correlation (Pearson’s r)</h2>
<p>Pearson’s Correlation is one of the most widely used statistical tests and it is used to compare two normally distributed continuous variables. In our case, we are interested in understanding if there is a correlation between petal and sepal length for each species of iris. To do so, we will filter for each species type and run Pearson’s Correlation.</p>
<pre class="r code-style"><code># Filtering for each type of iris

setosa &lt;- iris%&gt;%
  filter(Species == &quot;Setosa&quot;)
versicolor &lt;- iris%&gt;%
  filter(Species == &quot;Versicolor&quot;)
virginica &lt;- iris%&gt;%
  filter(Species == &quot;Virginica&quot;)

# Running Pearson&#39;s Correlation for each type of iris

setosa_r &lt;- cor.test(setosa$Petal.Length, setosa$Sepal.Length)


versicolor_r &lt;- cor.test(versicolor$Petal.Length, versicolor$Sepal.Length)


virginica_r &lt;- cor.test(virginica$Petal.Length, virginica$Sepal.Length)


#Viewing results

setosa_r</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  setosa$Petal.Length and setosa$Sepal.Length
## t = 1.9209, df = 48, p-value = 0.0607
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.01206954  0.50776233
## sample estimates:
##       cor 
## 0.2671758</code></pre>
<pre class="r code-style"><code>versicolor_r</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  versicolor$Petal.Length and versicolor$Sepal.Length
## t = 7.9538, df = 48, p-value = 2.586e-10
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6020680 0.8532995
## sample estimates:
##      cor 
## 0.754049</code></pre>
<pre class="r code-style"><code>virginica_r</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  virginica$Petal.Length and virginica$Sepal.Length
## t = 11.901, df = 48, p-value = 6.298e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7714542 0.9210172
## sample estimates:
##       cor 
## 0.8642247</code></pre>
<p> </p>
<p>As we can see, Versicolor and Virginica species had a significant positive correlation (P &lt; 0.05) between sepal and petal length, whereas Setosa did not (P &gt; 0.05)</p>
<p>Let’s take a look at these correlations using ggplot2!</p>
<pre class="r code-style"><code>iris%&gt;%
  ggplot(aes(x = Petal.Length, y = Sepal.Length, color = Species))+
  geom_point() +
  geom_smooth(method = &#39;lm&#39;, se = FALSE)+
  theme_bw() + 
  labs(x = &quot;Petal Length (cm)&quot;,
       y = &quot;Sepal Length (cm)&quot;,
       title = &quot;Correlation Between Petal and Sepal Lengths for Iris Species&quot;,
       color = &quot;Species&quot;)</code></pre>
<p><img src="R_Training_Module_Harris_Lab_files/figure-html/Creating%20point%20plot%20to%20show%20pearsons%20correlation-1.png" style="display: block; margin: auto;" /></p>
<p> </p>
<p>Next, let’s take a look at our respiratory health dataset. In particular, we want to understand if there is a correlation between lung capacity and age using Pearson’s correlation. To do so, we will use the following code:</p>
<pre class="r code-style"><code>#Pearson&#39;s Correlation
cor.test(lung_cap$Age, lung_cap$LungCap)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  lung_cap$Age and lung_cap$LungCap
## t = 38.476, df = 723, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7942660 0.8422217
## sample estimates:
##       cor 
## 0.8196749</code></pre>
<pre class="r code-style"><code>#Point plot displaying the significant correlation
lung_cap%&gt;%
  ggplot(aes(x = Age, y = LungCap))+
  geom_point() +
  geom_smooth(method = &#39;lm&#39;, se = FALSE)+
  theme_bw() + 
  labs(x = &quot;Age (years)&quot;,
       y = &quot;Lung Capacity&quot;,
       title = &quot;Correlation Between Age and Lung Capacity&quot;)</code></pre>
<p><img src="R_Training_Module_Harris_Lab_files/figure-html/Pearsons%20Correlation%20Example%202-1.png" style="display: block; margin: auto;" /></p>
<p> </p>
<p>Based on Pearson’s Correlation, there is a significant positive correlation between age and lung capacity (r = 0.82, P &lt; 0.05).</p>
<p>   </p>
</div>
<div id="pearsons-chi-squared-test" class="section level2" number="5.3">
<h2 number="5.3"><span class="header-section-number">5.3</span> Pearson’s Chi-squared Test</h2>
<p>Pearson’s Chi-squared Test are useful in determining relationships between two categorical variables with any number of levels. In this example, we will be looking at the relationship between species and above/below median sepal width, just as we displayed in the cross-tabulation in an earlier example!</p>
<pre class="r code-style"><code>#Displaying cross-tab that was developed in an earlier example
iris_kable%&gt;%
  group_by(Species, `Above/Below Median Sepal Width`)%&gt;%
  summarize(n=n())%&gt;%
  spread(Species, n)%&gt;%
  kable()%&gt;%
  add_header_above(c(&quot; &quot; = 1, &quot;Species&quot; = 3))%&gt;%
  add_header_above(c(&quot;Cross-tabulation of Iris Species and sepal Width (N = 150)&quot; = 4))%&gt;%
  kable_styling(bootstrap_options = c(&quot;condensed&quot;), full_width = F, font_size = 12)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;Species&#39;. You can override using the `.groups` argument.</code></pre>
<table class="table table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Cross-tabulation of Iris Species and sepal Width (N = 150)
</div>
</th>
</tr>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Species
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Above/Below Median Sepal Width
</th>
<th style="text-align:right;">
Setosa
</th>
<th style="text-align:right;">
Versicolor
</th>
<th style="text-align:right;">
Virginica
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Above Median
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
29
</td>
</tr>
<tr>
<td style="text-align:left;">
Below Median
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
21
</td>
</tr>
</tbody>
</table>
<pre class="r code-style"><code>#Running chi-squared test 
chisq.test(x = iris$Species, y = iris$Sepal.Width.Median)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  iris$Species and iris$Sepal.Width.Median
## X-squared = 43.973, df = 2, p-value = 2.828e-10</code></pre>
<p> </p>
<p>As we can see, the type of species is significantly associated with having above/below median sepal width (P &lt; 0.05). To gain more insight on the direction of effect, we can look at the cross-tab. We can see that 96% (48 out of 50) of Setosa Irises, 32% (16 out of 50) of Versicolor Irises, and 58% (29 out of 50) Virginica Irises have above median sepal widths. This association suggests that Setosa Irises have the largest sepal widths of the three species.</p>
<p>   </p>
</div>
<div id="mcnemar-test" class="section level2" number="5.4">
<h2 number="5.4"><span class="header-section-number">5.4</span> McNemar Test</h2>
<p>The McNemar Test is similar to chi-squared tests in that it is used on two categorical variables, except the categorical variables can only have 2 levels and the test is used for paired data. In an epidemiological sense, paired data means a measurement of an outcome is taken multiple times from the same participant or location. An example of this would be tracking the height or prevalence of diarrhea of children longitudinally. Sadly, in our case, we are not working with paired data, but I will still show example code for how to run the test in case you find yourself needing it.</p>
<pre class="r code-style"><code>#In this case, mcnemar.test() function requires that we input two variables that contain factor data:

# mcnemar.test(x = data$x_variable, y = data$y_variable, correct = TRUE)

# Uncomment the line above to use the mcnemar.test() function elsewhere.</code></pre>
<p>   </p>
</div>
<div id="students-t-test" class="section level2" number="5.5">
<h2 number="5.5"><span class="header-section-number">5.5</span> Student’s t Test</h2>
<p>At this point, we have used our Iris dataset to its fullest capacity, and it is time to switch things up. We will now be using our respiratory health dataset, lung_cap, for the remainder of the tutorial.</p>
<p>After looking at descriptive statistics, we will want to use a bivariate correlation test to understand if there are any associations between our variables of interest. The t test is helpful in determining if there are any statistically significant differences in means between two groups. The t test requires that we input one continuous variable and one categorical variable with two levels. Let’s compare the lung capacity of smokers versus nonsmokers.</p>
<pre class="r code-style"><code>#Running t test example
t.test(LungCap ~ Smoke, data = lung_cap, paired = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  LungCap by Smoke
## t = -3.6498, df = 117.72, p-value = 0.0003927
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.3501778 -0.4003548
## sample estimates:
##  mean in group no mean in group yes 
##          7.770188          8.645455</code></pre>
<p> </p>
<p>There is a significant difference in mean lung capacity between smokers and nonsmokers (P &lt; 0.05), in which smokers have greater mean lung capacity. However, this is a simple bivariate correlation and could be confounded by other variables. Particularly, we know age could be a confounding since our age range is only 3-19 and smoking is a habit usually developed later in life. Typically, smoking can hurt lung capacity, but in our case, it may be a better indication of age. Let’s check if smoking is associated to age using another t test.</p>
<pre class="r code-style"><code>#Running t test example
t.test(Age ~ Smoke, data = lung_cap, paired = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Age by Smoke
## t = -8.0803, df = 123.33, p-value = 5.023e-13
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.415842 -2.071612
## sample estimates:
##  mean in group no mean in group yes 
##          12.03549          14.77922</code></pre>
<p> </p>
<p>Based on the result of the t test, we can see a significant difference in age between smokers and nonsmokers (P &lt; 0.05). This confirms our hypothesis that age is also associated with smoking. We will take a look later at how the effect of this confounding relationship can be controlled for using regression analyses.</p>
<p>One additional note for t tests; we can also run a paired t test if the data meets meets the criteria. This is similar to how the McNemar Test requires paired data to be run. If our data includes multiple observations of one participant/location/item/etc, then a paired t test is needed. To do so, you would simply change the ‘paired’ option in the function to = TRUE.</p>
<p>   </p>
</div>
<div id="fishers-exact-test" class="section level2" number="5.6">
<h2 number="5.6"><span class="header-section-number">5.6</span> Fisher’s Exact Test</h2>
<p>Fisher’s exact test is similar to Pearson’s chi-squared test in that it is a comparison between two categorical variables, except Fisher’s exact test is used more appropriate for small sample sizes. A general rule of thumb is that Fisher’s exact test should be used when one of the frequencies of a 2x2 cross-tab is &lt; 5. Again, our example data does not meet this criteria for Fisher’s Exact Test, but example code is provided below.</p>
<pre class="r code-style"><code># Fisher&#39;s Exact Test Example Code

# fisher.test(x = data$x_variable, y = data$y_variable)

#Uncomment the line above to use the fisher.test() function.</code></pre>
<p> </p>
<hr />
</div>
</div>
<div id="regression-models" class="section level1" number="6">
<h1 number="6"><span class="header-section-number">6</span> Regression Models</h1>
<p>In global health research, we often want to see the effect of multiple variables on one outcome of interest through the use of regression models. Regression models can be very helpful in understanding the social determinants of certain outcomes, evaluating intervention impacts, and controlling for confounding by including potential confounders in the model. For this section, we will be relying upon the data from our respiratory health dataset, lung_cap.</p>
<p>   </p>
<div id="a-note-on-confounding" class="section level2" number="6.1">
<h2 number="6.1"><span class="header-section-number">6.1</span> A Note on Confounding</h2>
<p>As we discussed in the previous section, we believe there to be confounding between age and smoker status when determining their effects on lung capacity. For <a href="https://doi.org/10.1038/sj.ki.5002650">confounding</a> to exist, three criteria must be met:</p>
<ol style="list-style-type: decimal">
<li>The confounding variable must have an association with the outcome of interest.</li>
<li>The confounding variable must have an association with the exposure of interest.</li>
<li>The confounding variable must not be dependent on the exposure. Another way to consider this is that it must not be in the causal pathway between the exposure and outcome. This would be instead called a mediator.</li>
</ol>
<p>As we made note in the bivariate analysis section, we believe age could be a confounder in the relationship between smoking and lung capacity based on the age range of our sample. The figure below displays the relationship at hand:</p>
<p><img src="files/confounding.jpeg" />  </p>
<p>To understand this further and control for the effect of confounding, we will use simple linear regression and multiple linear regression models.</p>
<p> </p>
</div>
<div id="linear-regression" class="section level2" number="6.2">
<h2 number="6.2"><span class="header-section-number">6.2</span> Linear Regression</h2>
<div id="simple-linear-regression" class="section level3" number="6.2.1">
<h3 number="6.2.1"><span class="header-section-number">6.2.1</span> Simple Linear Regression</h3>
<p>Similar to how we used Pearson’s Correlation to understand the relationship between age and lung capacity, we can do so again with simple linear regression. Simple linear regression compares two continuous variables in a similar manner. The code for doing so is below:</p>
<pre class="r code-style"><code>#Simple linear regression model
lm_results &lt;- lm(LungCap ~ Age, data = lung_cap)

#Displaying summary of results
summary(lm_results)</code></pre>
<pre><code>## 
## Call:
## lm(formula = LungCap ~ Age, data = lung_cap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7799 -1.0203 -0.0005  0.9789  4.2650 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.14686    0.18353   6.249 7.06e-10 ***
## Age          0.54485    0.01416  38.476  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.526 on 723 degrees of freedom
## Multiple R-squared:  0.6719, Adjusted R-squared:  0.6714 
## F-statistic:  1480 on 1 and 723 DF,  p-value: &lt; 2.2e-16</code></pre>
<p> </p>
<p>We can see the correlation coefficient for age this time is only r = 0.54, as compared to r = 0.82 when we originally ran Pearson’s r Correlation. This is because the linear model is now accounting for the intercept at 1.15, as opposed to 0, so the slope is decreased.</p>
<p>The final linear model can be read as: Lung Capacity = 1.15 + 0.54 * (Age)</p>
<p>Similarly, we can run simple linear regression with a continuous variable as the output and a categorical variable as the covariate. Let’s look into the relationship between smoking and lung capacity now.</p>
<pre class="r code-style"><code>#Simple linear regression model, this time with smoking as the covariate of interest
lm_results &lt;- lm(LungCap ~ Smoke, data = lung_cap)

#Displaying summary of results
summary(lm_results)</code></pre>
<pre><code>## 
## Call:
## lm(formula = LungCap ~ Smoke, data = lung_cap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.2632 -1.7202  0.1048  1.9048  6.9048 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.7702     0.1041   74.64   &lt;2e-16 ***
## Smokeyes      0.8753     0.3194    2.74   0.0063 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.65 on 723 degrees of freedom
## Multiple R-squared:  0.01028,    Adjusted R-squared:  0.008908 
## F-statistic: 7.507 on 1 and 723 DF,  p-value: 0.006297</code></pre>
<p> </p>
<p>As we suspected, there is a similar relationship. However, we interpret the results slightly differently. Since smoking was a categorical variable, we now have an instance where a variable was ‘dummy’ coded with a reference category. This means that the model is comparing those who smoke to a reference category of those who do not smoke. ‘Dummy’ primarily comes in handy when you have a categorical variable with 3 or more options.</p>
<p>Our final model now takes the format: Lung Capacity = 7.77 + 0.88 * (Smoker)</p>
<p>If a person smokes, then ‘Smoker’ is equal to 1 and the lung capacity is 8.65, which is also the average lung capacity of all smokers. If a person does not smoke, then ‘Smoker’ is equal to 0 and the lung capacity is 7.77, which is also the average lung capacity of all non-smokers.</p>
<p>However, given the current state of medical research, smoking should not increase one’s lung capacity. To understand this confounding relationship between age and smoking, we will use multiple linear regression.</p>
<p> </p>
</div>
<div id="multiple-linear-regression" class="section level3" number="6.2.2">
<h3 number="6.2.2"><span class="header-section-number">6.2.2</span> Multiple Linear Regression</h3>
<p>Again, we suspect there to be a confounding relationship between age and smoking status, so to help control for this we will be using multiple linear regression. Our outcome of interest, lung capacity, is still a continuous variable, but with multiple linear regression we will be including age and smoking status as covariates in the model. Additionally, since we know age and smoking status to already be correlated, we will be testing for multicollinearity in our regression model using variance inflation factors. The following code shows how to do so and displays our results:</p>
<pre class="r code-style"><code>#Multiple linear regression model
lm_results &lt;- lm(LungCap ~ Age + Smoke, data = lung_cap)

#Displaying summary of results
summary(lm_results)</code></pre>
<pre><code>## 
## Call:
## lm(formula = LungCap ~ Age + Smoke, data = lung_cap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8559 -1.0289 -0.0363  1.0083  4.1995 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.08572    0.18299   5.933 4.61e-09 ***
## Age          0.55540    0.01438  38.628  &lt; 2e-16 ***
## Smokeyes    -0.64859    0.18676  -3.473 0.000546 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.514 on 722 degrees of freedom
## Multiple R-squared:  0.6773, Adjusted R-squared:  0.6764 
## F-statistic: 757.5 on 2 and 722 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r code-style"><code>#Determining variance inflation factors (VIF) to understand multicollinearity
car::vif(lm_results)</code></pre>
<pre><code>##      Age    Smoke 
## 1.046703 1.046703</code></pre>
<p> </p>
<p>Interesting results! First, we see that age and smoking are still significantly associated with lung capacity (P &lt; 0.05), but there is now a negative effect from smoking. Controlling for age, we can see now that being a smoker leads to an average 0.65 <strong>decrease</strong> in lung capacity. This contradicts our earlier relationship we were witnessing from bivariate correlation tests where being a smoker seemed to increase lung capacity, but now we know that age is an important confounder since it switches the direction of effect.</p>
<p>Multicollinearity can skew the results of a regression model, but since our variance inflation factors are close to 1, this is not a concern in this instance.</p>
<p> </p>
</div>
</div>
<div id="logistic-regression" class="section level2" number="6.3">
<h2 number="6.3"><span class="header-section-number">6.3</span> Logistic Regression</h2>
<p>Not all outcomes of interest will be continuous variables like lung capacity. Often, we will be working with binary outcomes like child mortality or diarrheal prevalence. Logistic regression models are useful in scenarios where an outcome is binary. However, unlike linear regression models, the coefficients of the model are actually log-transformed odds ratios. More information on odds ratios can be found <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2938757/">here</a>. We will have the added step of converting them from being log-transformed this time.</p>
<p>In this example, let’s explore some of the determinants of smoking. It is important to note that our example dataset is lacking several other important determinants of smoking like wealth and education, so this example (and every other for that matter) should only be used for educational purposes.</p>
<pre class="r code-style"><code>#First, we need to change the factor levels to a binary 0 (nonsmoker) or 1 (smoker)
lung_cap$Smoke &lt;- fct_recode(lung_cap$Smoke,
  &quot;0&quot; = &quot;no&quot;,
  &quot;1&quot; = &quot;yes&quot;
)

#Logistic regression model
log_results &lt;- glm(Smoke ~ Age + Gender + Height + LungCap, data = lung_cap, family = &quot;binomial&quot;) # The &#39;family&#39; option allows us to select for a logistic regression model!
summary_results &lt;- summary(log_results)

#Now, we need to extract and exponentiate the odds ratios since they are log-transformed
#Extracting p values from the logistic regression
p_values &lt;- coef(summary_results)[,4]%&gt;%
  round(digits = 4)
#Extracting coefficients from the logistic regression and turning into odds ratios
odds &lt;- coef(log_results)%&gt;%
  exp()%&gt;%
  round(digits = 4)

#Storing into a dataframe
results &lt;- data.frame(odds, p_values)

results%&gt;%
  kable()%&gt;%
  add_header_above(c(&quot;Logistic Regression Model Results for Smoking Status (N = 725)&quot; = 3))%&gt;%
  kable_paper(bootstrap_options = c(&quot;striped&quot;,&quot;condensed&quot;), font_size = 12, full_width = F)</code></pre>
<table class=" lightable-paper" style="font-size: 12px; font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Logistic Regression Model Results for Smoking Status (N = 725)
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
odds
</th>
<th style="text-align:right;">
p_values
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
1.3089
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:left;">
Gendermale
</td>
<td style="text-align:right;">
0.8693
</td>
<td style="text-align:right;">
0.6039
</td>
</tr>
<tr>
<td style="text-align:left;">
Height
</td>
<td style="text-align:right;">
1.1813
</td>
<td style="text-align:right;">
0.0004
</td>
</tr>
<tr>
<td style="text-align:left;">
LungCap
</td>
<td style="text-align:right;">
0.5605
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>From the logistic regression model we can see age, height, and lung capacity to be significantly associated with smoking status (P &lt; 0.05). To interpret the odds ratio, if it is &gt; 1 it means there is an increase in odds of being a smoker, whereas if the odds ratio is &lt; 1, it means there is a decrease in odds of being a smoker. So for age, there was an increase in odds between each incremental year old and being a smoker. This positive association is similarly seen with height. However, a decrease in odds was observed with smoking and better lung capacity.</p>
<p> </p>
</div>
<div id="poisson-regression" class="section level2" number="6.4">
<h2 number="6.4"><span class="header-section-number">6.4</span> Poisson Regression</h2>
<p> </p>
<p>As explained previously, logistic regression models return odds ratios, however, this can overestimate the prevalence if the outcome is not rare. Poisson regression models are typically used with ordinal count data (1, 2, 3, 4, etc.), but can also be used with binary data (0 or 1). Poisson regressions also return log-transformed prevalence ratios rather than log-transformed odds ratios. Further discussion on the use of Poisson versus logistic regression can be found <a href="https://doi.org/10.1002/sim.7059">here</a>.</p>
<p>Let’s explore the same relationships but using Poisson Regression.</p>
<pre class="r code-style"><code>#First, we need to change the factor levels to a binary 0 (nonsmoker) or 1 (smoker)
lung_cap$Smoke &lt;- fct_recode(lung_cap$Smoke,
  &quot;0&quot; = &quot;no&quot;,
  &quot;1&quot; = &quot;yes&quot;
)

lung_cap$Smoke &lt;- as.numeric(as.character(lung_cap$Smoke))
  

#Poisson regression model
log_results &lt;- glm(Smoke ~ Age + Gender + Height + LungCap, data = lung_cap, family = &quot;poisson&quot;) # The &#39;family&#39; option allows us to select for a poisson regression model!
summary_results &lt;- summary(log_results)

#Now, we need to extract and exponentiate the prevalence ratios since they are log-transformed
#Extracting p values from the poisson regression
p_values &lt;- coef(summary_results)[,4]%&gt;%
  round(digits = 4)
#Extracting coefficients from the poisson regression and turning into odds ratios
prevalence_ratio &lt;- coef(log_results)%&gt;%
  exp()%&gt;%
  round(digits = 4)

#Storing into a dataframe
results &lt;- data.frame(prevalence_ratio, p_values)

results%&gt;%
  kable()%&gt;%
  add_header_above(c(&quot;Poisson Regression Model Results for Smoking Status (N = 725)&quot; = 3))%&gt;%
  kable_paper(bootstrap_options = c(&quot;striped&quot;,&quot;condensed&quot;), font_size = 12, full_width = F)</code></pre>
<table class=" lightable-paper" style="font-size: 12px; font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Poisson Regression Model Results for Smoking Status (N = 725)
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
prevalence_ratio
</th>
<th style="text-align:right;">
p_values
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
1.2518
</td>
<td style="text-align:right;">
0.0001
</td>
</tr>
<tr>
<td style="text-align:left;">
Gendermale
</td>
<td style="text-align:right;">
0.8891
</td>
<td style="text-align:right;">
0.6308
</td>
</tr>
<tr>
<td style="text-align:left;">
Height
</td>
<td style="text-align:right;">
1.1484
</td>
<td style="text-align:right;">
0.0009
</td>
</tr>
<tr>
<td style="text-align:left;">
LungCap
</td>
<td style="text-align:right;">
0.6219
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>As we can see, the direction of effect remains the same for each predictor in our model, except we now have prevalence ratios rather than odds ratios. In this case, rather than saying there was an ‘increase in odds between age and smoking status,’ we would say there was an ‘increase in risk between age and smoking status.’ This small emphasis on odds versus risk has large implications!</p>
<hr />
</div>
</div>
<div id="intervention-impact-evaluation" class="section level1" number="7">
<h1 number="7"><span class="header-section-number">7</span> Intervention Impact Evaluation</h1>
<p>For this next example on how to conduct intervention impact evaluations, I am going to create a hypothetical situation based on our respiratory health dataset. The following paragraph is entirely made up but will set the scene for a hypothetical <a href="http://dx.doi.org/10.1136/emj.20.2.164">randomized-controlled trial</a> of a public health messaging campaign.</p>
<p>Smoking among young people has increased drastically in North Carolina over the last decade (fictional source). We are interested in the effectiveness of a educational program against smoking and are considering incorporating it into the school curriculum in North Carolina. Young people will participate in the course over 3 days. Students will be enrolled in the study if they are between 12-18 years old and attend one of 3 North Carolina Public Schools chosen for the study. Students will be followed up with at one week and four weeks following the course to understand their smoking habits.</p>
<p>I am now going to manipulate our respiratory health dataset to fit the study. We only want students aged 13-18 years and will be randomly assigning them to a treatment or control group. We will also need to make up what school they are from.</p>
<pre class="r code-style"><code># Selecting people only aged 12-18 years
rct &lt;- lung_cap%&gt;%
  filter(Age &gt;= 12 &amp; Age &lt;= 18)

#N = 397



# Enrolling them randomly in a study arm -- 1 for intervention, 0 for control
# First, getting the number of participants
N &lt;- nrow(rct)
# Now assigning to study arms
# install.packages(&quot;randomizr&quot;)
library(randomizr)
assignment &lt;- complete_ra(N = N, m = 199) # Specifying that we want 199 students in our treatment group

#Attaching study arm assignment to our main rct dataset
rct &lt;- rct%&gt;%
  mutate(assignment = assignment)



# Assigning a North Carolina Public School for each student
school &lt;- complete_ra(N = N, m_each = c(132, 132, 133), conditions = c(&quot;School 1&quot;, &quot;School 2&quot;, &quot;School 3&quot;))

rct &lt;- rct%&gt;%
  mutate(school = school)</code></pre>
<p> </p>
<p>Now that we have the study assignments, we are almost ready to do the evaluation. <strong>We are going to assume that our ‘rct’ dataset contains data collected at the endline (4 week mark) of our study.</strong> The educational program has already happened! We are now interested in seeing if there was a significant effect on our primary outcome of interest, smoking status.</p>
<p>To do so, we will be creating unadjusted and adjusted models using Poisson regression. In an unadjusted model, we will not be controlling for confounders and will only be comparing smoking status to the study assignment (smoke ~ assignment). In the adjusted model, however, we will be controlling for confounders that are shown to be adequately associated at the P &lt; 0.2 level with our outcome of interest, smoking status. To also be conservative, we will be using robust standard errors that account for clustering at the school level using the <a href="https://www.stat.berkeley.edu/~census/mlesan.pdf">Huber Sandwich Estimator</a>. The process will make more sense as you look at the code, but just remember our overall research question: <strong>What effect does an educational program against smoking have on the smoking habits of 12-18 year olds?</strong></p>
<p>First, let’s see if there are any covariates we should be concerned about for our adjusted model.</p>
<pre class="r code-style"><code># Rather than manually running a Poisson regression for each covariate of interest, I will develop a function to iterate through each one. 

# Function development
adjusted_model_covariates &lt;- function(outcome, data, covariate, conf = .2, covariate_list = tibble(covariate = character())){
  #outcome represents the outcome of interest for the regression model
  #data is the dataset you will run the regression on
  #covariate is the list of covariates to iterate through one by one to determine if they meet the P &lt; 0.2 threshhold
  #covariate_list is a empty dataframe to contain covariates in that meet the threshhold
  
  for (i in covariate){
    df &lt;- data%&gt;%
      dplyr::select(c(outcome, i))
    names(df) &lt;- c(&quot;outcome&quot;, &quot;i&quot;)
    
    #Running bivariate test
    regr &lt;- glm(outcome ~ i, data = df, family = &quot;poisson&quot;)
    
    #Subsetting p values
    p_values &lt;- coef(summary(regr))[,4]%&gt;%
      data.frame()
    
    p &lt;- p_values[-1,]
    
    #determining if p value meets P &lt; 0.2 threshold
    for (j in 1:length(p)){
      if(p[j] &lt; 0.2){
        #if P &lt; 0.2, it stores the covariate name
        covariate_list &lt;- rbind(covariate_list, i)
      }
    }
  }
  return(covariate_list)
}

# End function development


# Now, we will select our list of covariates to test for. 
covariate &lt;- c(&quot;LungCap&quot;, &quot;Age&quot;, &quot;Height&quot;, &quot;Gender&quot;, &quot;Caesarean&quot;)
# And our outcome of interest
outcome &lt;- &quot;Smoke&quot;

# Poisson regression needs numeric data type so I convert it here from a factor. 
rct[[outcome]] &lt;- as.numeric(as.character(rct[[outcome]]))

# Now, we run the function to see if any covariates meet the P &lt; 0.2 threshold
covariates_results &lt;- adjusted_model_covariates(data = rct, outcome = outcome, covariate = covariate)
#covariates_results shows the covariates that are beneath this threshold. These covariates are to be included in the adjusted model.

covariates_results</code></pre>
<pre><code>##   X.Age.
## 1    Age</code></pre>
<p> </p>
<p>As we can see, Age is the only covariate that was below the P &lt; 0.2 threshhold from bivariate testing with Poisson regression. This aligns with what we found in the previous sections, in which age was associated with smoking.</p>
<p>Now, we are ready to evaluate the impact of the intervention! To do so, we will develop our unadjusted model, then our adjusted model while controlling for age (by including it in the model), and then represent the results in a formatted table. The next section presents a lot of code relative to other sections, so bear with me!</p>
<pre class="r code-style"><code># Package loading
# install.packages(&quot;sandwich&quot;)
library(sandwich)


#Running unadjusted model ----


#Running unadjusted model
unadjusted &lt;- glm(Smoke ~ assignment, data = rct, family = &quot;poisson&quot;)

#Accounting for clustering using sandwich package
data_sandwich &lt;- unadjusted%&gt;%
  vcovCL(cluster = rct$school) #this is where we account for clustering at the school level using the Huber Sandwich estimator (can read more into it)

#Hand calculates the robust standard errors after accounting for clustering
#There are simpler ways to do this, but this should work too.
#Important to note that the code below already exponentiates the coefficients and std errors
std.err &lt;- sqrt(diag(data_sandwich))
robust_unadjusted &lt;- tibble(&quot;pr&quot;= exp(coef(unadjusted)), &quot;Std. Error&quot; = exp(std.err),
                            &quot;Pr(&gt;|z|)&quot; = 2 * pnorm(abs(coef(unadjusted)/std.err), lower.tail=FALSE),
                            &quot;LL&quot; = exp((coef(unadjusted)) - 1.96 * (std.err)),
                            &quot;UL&quot; = exp((coef(unadjusted)) + 1.96 * (std.err)))

#Creating readable 95% CI based on lower limit and upper limit
robust_unadjusted &lt;- tibble(robust_unadjusted,
                            CI = paste(&quot;[&quot;, as.character(round(robust_unadjusted$LL, digits = 3)), &quot;,&quot;, as.character(round(robust_unadjusted$UL, digits = 3)), &quot;]&quot;))


#Storing values to final results tibble
unadjusted_pr &lt;- robust_unadjusted$pr[2]
unadjusted_ci &lt;- robust_unadjusted$CI[2]
unadjusted_p &lt;- robust_unadjusted$`Pr(&gt;|z|)`[2]
n &lt;- length(rct$assignment) #number of observations



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#Running adjusted model similar to the unadjusted model above. ----


#Running adjusted model based on what we found in previous code chunk
adjusted &lt;- glm(Smoke ~ assignment + Age, data = rct, family = &quot;poisson&quot;) #This will change based on your outcome of interest and whatever covariates are at P &lt;0.2 

data_sandwich &lt;- adjusted%&gt;%
  vcovCL(cluster = rct$school) #Again, accounting for clustering at the village level

#Hand calculation again
#Important to note that the code below already exponentiates the coefficients and std errors
std.err &lt;- sqrt(diag(data_sandwich))
robust_adjusted &lt;- tibble(&quot;pr&quot;= exp(coef(adjusted)), &quot;Std. Error&quot; = exp(std.err),
                          &quot;Pr(&gt;|z|)&quot; = 2 * pnorm(abs(coef(adjusted)/std.err), lower.tail=FALSE),
                          &quot;LL&quot; = exp(coef(adjusted) - 1.96 * (std.err)),
                          &quot;UL&quot; = exp(coef(adjusted) + 1.96 * (std.err)))

#Creating readable 95% CI based on LL and UL
robust_adjusted &lt;- tibble(robust_adjusted,
                          CI = paste(&quot;[&quot;, as.character(round(robust_adjusted$LL, digits = 3)), &quot;,&quot;, as.character(round(robust_adjusted$UL, digits = 3)), &quot;]&quot;))


#Storing values to final results tibble
adjusted_pr &lt;- robust_adjusted$pr[2]
adjusted_ci &lt;- robust_adjusted$CI[2]
adjusted_p &lt;- robust_adjusted$`Pr(&gt;|z|)`[2]


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



# storing results in a nice format ----
outcome_result &lt;- tibble(outcome = outcome,
                         unadjusted_pr = unadjusted_pr,
                         unadjusted_ci = unadjusted_ci,
                         unadjusted_p = unadjusted_p,
                         adjusted_pr = adjusted_pr,
                         adjusted_ci = adjusted_ci,
                         adjusted_p = adjusted_p,
                         n = n
                         )


outcome_result%&gt;%
  kable()%&gt;%
  add_header_above(c(&quot;Intervention Impact Evaluation (N = 397)&quot; = 8))%&gt;%
  kable_paper(bootstrap_options = c(&quot;striped&quot;,&quot;condensed&quot;), font_size = 12, full_width = F)</code></pre>
<table class=" lightable-paper" style="font-size: 12px; font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="8">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Intervention Impact Evaluation (N = 397)
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
outcome
</th>
<th style="text-align:right;">
unadjusted_pr
</th>
<th style="text-align:left;">
unadjusted_ci
</th>
<th style="text-align:right;">
unadjusted_p
</th>
<th style="text-align:right;">
adjusted_pr
</th>
<th style="text-align:left;">
adjusted_ci
</th>
<th style="text-align:right;">
adjusted_p
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Smoke
</td>
<td style="text-align:right;">
1.243719
</td>
<td style="text-align:left;">
[ 0.946 , 1.634 ]
</td>
<td style="text-align:right;">
0.1175319
</td>
<td style="text-align:right;">
1.182234
</td>
<td style="text-align:left;">
[ 0.833 , 1.678 ]
</td>
<td style="text-align:right;">
0.3484099
</td>
<td style="text-align:right;">
397
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>Now that we have our final results for the intervention impact evaluation in a formatted table, what do they mean?</p>
<p>Presented in the table are the unadjusted and adjusted prevalence ratios, the 95% confidence intervals based on robust standard errors, and the number (n) of study participants.</p>
<p>Primarily, since P &gt; 0.05, we can conclude that our educational program against smoking did not have any influence on the smoking habits of the study participants (This is to be expected since the study arm assignments were randomly assigned to fictional data).</p>
<p>Finally, congrats! You just evaluated the impact of a fictional randomized-controlled trial and now know how to do so for future ones in R!</p>
<hr />
</div>
<div id="conclusion" class="section level1" number="8">
<h1 number="8"><span class="header-section-number">8</span> Conclusion</h1>
<p>This training module was meant to introduce you to helpful tools in R to create tables and visualizations, as well as walking through a bivariate data analyses and regression models. This module only touches the surface of everything R is capable of! There are vast resources available, and it is recommended you check out all of the many resources that have been linked throughout this document!</p>
<p>Have fun! Best of luck!</p>
<hr />
</div>

<center>
  <p>Copyright &copy; 2021 Jeremy Lowe. All rights reserved.</p>
</center>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
